-- Run once by an authorized SUPPLY_CHAIN_DEV deployment role.
-- Runtime forecasting code performs no DDL.
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_DEV.FORECASTING;

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.FORECASTING.RUN_METADATA (
    RUN_ID VARCHAR(36) NOT NULL,
    STARTED_AT TIMESTAMP_NTZ NOT NULL,
    ENDED_AT TIMESTAMP_NTZ,
    STATUS VARCHAR(16) NOT NULL,
    TRAINING_START DATE,
    TRAINING_END DATE,
    HORIZON NUMBER(5, 0) NOT NULL,
    SERIES_ATTEMPTED NUMBER(12, 0) NOT NULL,
    SERIES_SUCCEEDED NUMBER(12, 0) NOT NULL,
    SERIES_FALLBACK NUMBER(12, 0) NOT NULL,
    SERIES_FAILED NUMBER(12, 0) NOT NULL,
    RECORDS_PRODUCED NUMBER(12, 0) NOT NULL,
    SOURCE_VERSION VARCHAR(128),
    FAILURE_REASON VARCHAR(2000),
    INPUT_FINGERPRINT VARCHAR(64),
    COVERAGE_START DATE,
    OBSERVED_THROUGH DATE,
    MODEL_VERSION VARCHAR(128) NOT NULL,
    CONSTRAINT PK_FORECAST_RUN_METADATA PRIMARY KEY (RUN_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.FORECASTING.MODEL_EVALUATION (
    RUN_ID VARCHAR(36) NOT NULL,
    PRODUCT_ID VARCHAR(64) NOT NULL,
    WAREHOUSE_KEY VARCHAR(64) NOT NULL,
    MODEL_NAME VARCHAR(128) NOT NULL,
    MAE FLOAT,
    RMSE FLOAT,
    WAPE FLOAT,
    TEST_MAE FLOAT,
    TEST_RMSE FLOAT,
    TEST_WAPE FLOAT,
    BASELINE_MAE FLOAT,
    BASELINE_RMSE FLOAT,
    BASELINE_WAPE FLOAT,
    CANDIDATE_MAE FLOAT,
    CANDIDATE_RMSE FLOAT,
    CANDIDATE_WAPE FLOAT,
    SELECTED_MODEL VARCHAR(128),
    FALLBACK_USED BOOLEAN NOT NULL,
    TRAINING_START DATE,
    TRAINING_END DATE,
    VALIDATION_START DATE,
    VALIDATION_END DATE,
    CONSTRAINT PK_FORECAST_MODEL_EVALUATION PRIMARY KEY
        (RUN_ID, PRODUCT_ID, WAREHOUSE_KEY, MODEL_NAME)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.FORECASTING.CURRENT_FORECASTS (
    RUN_ID VARCHAR(36) NOT NULL,
    GENERATED_AT TIMESTAMP_NTZ NOT NULL,
    FORECAST_DATE DATE NOT NULL,
    PRODUCT_ID VARCHAR(64) NOT NULL,
    PRODUCT_KEY VARCHAR(64),
    WAREHOUSE_KEY VARCHAR(64) NOT NULL,
    HORIZON NUMBER(5, 0) NOT NULL,
    PREDICTED_DEMAND FLOAT NOT NULL,
    LOWER_BOUND FLOAT,
    UPPER_BOUND FLOAT,
    MODEL_NAME VARCHAR(128) NOT NULL,
    FALLBACK_USED BOOLEAN NOT NULL,
    FALLBACK_REASON VARCHAR(1000),
    UNCERTAINTY_METHOD VARCHAR(128),
    RESIDUAL_SAMPLE_COUNT NUMBER(12, 0),
    TRAINING_START DATE,
    TRAINING_END DATE,
    SOURCE_VERSION VARCHAR(128),
    MODEL_VERSION VARCHAR(128) NOT NULL,
    CONSTRAINT PK_FORECAST_CURRENT_FORECASTS PRIMARY KEY
        (RUN_ID, FORECAST_DATE, PRODUCT_ID, WAREHOUSE_KEY)
);
