-- SupplySight Phase 3 RAW source tables and ingestion audit tables.
-- Source values are stored as VARCHAR to preserve the original CSV representation.
-- Primary keys document business grain. Snowflake does not enforce standard-table keys.

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.PRODUCTS (
    PRODUCT_ID VARCHAR NOT NULL,
    SKU VARCHAR NOT NULL,
    PRODUCT_NAME VARCHAR NOT NULL,
    CATEGORY VARCHAR NOT NULL,
    SUBCATEGORY VARCHAR,
    UNIT_COST VARCHAR NOT NULL,
    LIST_PRICE VARCHAR NOT NULL,
    LAUNCH_DATE VARCHAR NOT NULL,
    ACTIVE_FLAG VARCHAR NOT NULL,
    REORDER_POINT VARCHAR NOT NULL,
    _INGESTED_AT TIMESTAMP_TZ NOT NULL,
    _SOURCE_FILE VARCHAR NOT NULL,
    _BATCH_ID VARCHAR NOT NULL,
    _SOURCE_SYSTEM VARCHAR NOT NULL,
    _ROW_HASH VARCHAR NOT NULL,
    _QUALITY_STATUS VARCHAR NOT NULL,
    _QUALITY_ISSUES ARRAY,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.WAREHOUSES (
    WAREHOUSE_ID VARCHAR NOT NULL,
    WAREHOUSE_NAME VARCHAR NOT NULL,
    REGION VARCHAR NOT NULL,
    COUNTRY VARCHAR NOT NULL,
    CAPACITY_UNITS VARCHAR NOT NULL,
    _INGESTED_AT TIMESTAMP_TZ NOT NULL,
    _SOURCE_FILE VARCHAR NOT NULL,
    _BATCH_ID VARCHAR NOT NULL,
    _SOURCE_SYSTEM VARCHAR NOT NULL,
    _ROW_HASH VARCHAR NOT NULL,
    _QUALITY_STATUS VARCHAR NOT NULL,
    _QUALITY_ISSUES ARRAY,
    PRIMARY KEY (WAREHOUSE_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.SUPPLIERS (
    SUPPLIER_ID VARCHAR NOT NULL,
    SUPPLIER_NAME VARCHAR NOT NULL,
    REGION VARCHAR NOT NULL,
    COUNTRY VARCHAR NOT NULL,
    LEAD_TIME_DAYS VARCHAR NOT NULL,
    LEAD_TIME_STD_DAYS VARCHAR NOT NULL,
    ON_TIME_RATE VARCHAR NOT NULL,
    QUALITY_RATE VARCHAR NOT NULL,
    COST_FACTOR VARCHAR NOT NULL,
    ACTIVE_FLAG VARCHAR NOT NULL,
    _INGESTED_AT TIMESTAMP_TZ NOT NULL,
    _SOURCE_FILE VARCHAR NOT NULL,
    _BATCH_ID VARCHAR NOT NULL,
    _SOURCE_SYSTEM VARCHAR NOT NULL,
    _ROW_HASH VARCHAR NOT NULL,
    _QUALITY_STATUS VARCHAR NOT NULL,
    _QUALITY_ISSUES ARRAY,
    PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.CUSTOMERS (
    CUSTOMER_ID VARCHAR NOT NULL,
    CUSTOMER_SEGMENT VARCHAR NOT NULL,
    REGION VARCHAR NOT NULL,
    COUNTRY VARCHAR NOT NULL,
    SIGNUP_DATE VARCHAR NOT NULL,
    _INGESTED_AT TIMESTAMP_TZ NOT NULL,
    _SOURCE_FILE VARCHAR NOT NULL,
    _BATCH_ID VARCHAR NOT NULL,
    _SOURCE_SYSTEM VARCHAR NOT NULL,
    _ROW_HASH VARCHAR NOT NULL,
    _QUALITY_STATUS VARCHAR NOT NULL,
    _QUALITY_ISSUES ARRAY,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.ORDERS (
    ORDER_ID VARCHAR NOT NULL,
    ORDER_LINE_ID VARCHAR NOT NULL,
    ORDER_DATE VARCHAR NOT NULL,
    CUSTOMER_ID VARCHAR NOT NULL,
    PRODUCT_ID VARCHAR NOT NULL,
    WAREHOUSE_ID VARCHAR NOT NULL,
    QUANTITY VARCHAR NOT NULL,
    UNIT_PRICE VARCHAR NOT NULL,
    DISCOUNT_PCT VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    PROMISED_DELIVERY_DATE VARCHAR NOT NULL,
    _INGESTED_AT TIMESTAMP_TZ NOT NULL,
    _SOURCE_FILE VARCHAR NOT NULL,
    _BATCH_ID VARCHAR NOT NULL,
    _SOURCE_SYSTEM VARCHAR NOT NULL,
    _ROW_HASH VARCHAR NOT NULL,
    _QUALITY_STATUS VARCHAR NOT NULL,
    _QUALITY_ISSUES ARRAY,
    PRIMARY KEY (ORDER_LINE_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.INVENTORY_SNAPSHOTS (
    SNAPSHOT_DATE VARCHAR NOT NULL,
    WAREHOUSE_ID VARCHAR NOT NULL,
    PRODUCT_ID VARCHAR NOT NULL,
    ON_HAND_UNITS VARCHAR NOT NULL,
    RESERVED_UNITS VARCHAR NOT NULL,
    AVAILABLE_UNITS VARCHAR NOT NULL,
    IN_TRANSIT_UNITS VARCHAR NOT NULL,
    INVENTORY_VALUE VARCHAR NOT NULL,
    _INGESTED_AT TIMESTAMP_TZ NOT NULL,
    _SOURCE_FILE VARCHAR NOT NULL,
    _BATCH_ID VARCHAR NOT NULL,
    _SOURCE_SYSTEM VARCHAR NOT NULL,
    _ROW_HASH VARCHAR NOT NULL,
    _QUALITY_STATUS VARCHAR NOT NULL,
    _QUALITY_ISSUES ARRAY,
    PRIMARY KEY (SNAPSHOT_DATE, WAREHOUSE_ID, PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.PURCHASE_ORDERS (
    PURCHASE_ORDER_ID VARCHAR NOT NULL,
    PO_LINE_ID VARCHAR NOT NULL,
    SUPPLIER_ID VARCHAR NOT NULL,
    WAREHOUSE_ID VARCHAR NOT NULL,
    PRODUCT_ID VARCHAR NOT NULL,
    ORDER_DATE VARCHAR NOT NULL,
    EXPECTED_DELIVERY_DATE VARCHAR NOT NULL,
    RECEIVED_DATE VARCHAR,
    ORDERED_QUANTITY VARCHAR NOT NULL,
    RECEIVED_QUANTITY VARCHAR NOT NULL,
    UNIT_COST VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    _INGESTED_AT TIMESTAMP_TZ NOT NULL,
    _SOURCE_FILE VARCHAR NOT NULL,
    _BATCH_ID VARCHAR NOT NULL,
    _SOURCE_SYSTEM VARCHAR NOT NULL,
    _ROW_HASH VARCHAR NOT NULL,
    _QUALITY_STATUS VARCHAR NOT NULL,
    _QUALITY_ISSUES ARRAY,
    PRIMARY KEY (PO_LINE_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.SHIPMENTS (
    SHIPMENT_ID VARCHAR NOT NULL,
    ORDER_LINE_ID VARCHAR NOT NULL,
    WAREHOUSE_ID VARCHAR NOT NULL,
    SHIP_DATE VARCHAR NOT NULL,
    DELIVERY_DATE VARCHAR,
    SHIPPED_QUANTITY VARCHAR NOT NULL,
    SHIPMENT_STATUS VARCHAR NOT NULL,
    CARRIER VARCHAR NOT NULL,
    _INGESTED_AT TIMESTAMP_TZ NOT NULL,
    _SOURCE_FILE VARCHAR NOT NULL,
    _BATCH_ID VARCHAR NOT NULL,
    _SOURCE_SYSTEM VARCHAR NOT NULL,
    _ROW_HASH VARCHAR NOT NULL,
    _QUALITY_STATUS VARCHAR NOT NULL,
    _QUALITY_ISSUES ARRAY,
    PRIMARY KEY (SHIPMENT_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.RETURNS (
    RETURN_ID VARCHAR NOT NULL,
    ORDER_LINE_ID VARCHAR NOT NULL,
    RETURN_DATE VARCHAR NOT NULL,
    QUANTITY VARCHAR NOT NULL,
    REASON VARCHAR NOT NULL,
    DISPOSITION VARCHAR NOT NULL,
    REFUND_AMOUNT VARCHAR NOT NULL,
    _INGESTED_AT TIMESTAMP_TZ NOT NULL,
    _SOURCE_FILE VARCHAR NOT NULL,
    _BATCH_ID VARCHAR NOT NULL,
    _SOURCE_SYSTEM VARCHAR NOT NULL,
    _ROW_HASH VARCHAR NOT NULL,
    _QUALITY_STATUS VARCHAR NOT NULL,
    _QUALITY_ISSUES ARRAY,
    PRIMARY KEY (RETURN_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.INGESTION_BATCHES (
    BATCH_ID VARCHAR NOT NULL,
    SOURCE_SYSTEM VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    SOURCE_FILE_COUNT NUMBER(10, 0) NOT NULL DEFAULT 0,
    SOURCE_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    MERGED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    INSERTED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    UPDATED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    UNCHANGED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    WARNING_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    QUARANTINED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    QUARANTINE_RECORD_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    HARD_REJECTED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    ERROR_MESSAGE VARCHAR,
    PRIMARY KEY (BATCH_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.INGESTION_BATCH_FILES (
    BATCH_ID VARCHAR NOT NULL,
    SOURCE_FILE VARCHAR NOT NULL,
    ENTITY_NAME VARCHAR NOT NULL,
    FILE_SHA256 VARCHAR NOT NULL,
    FILE_SIZE_BYTES NUMBER(18, 0) NOT NULL,
    STATUS VARCHAR NOT NULL,
    SOURCE_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    MERGED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    INSERTED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    UPDATED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    UNCHANGED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    WARNING_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    QUARANTINED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    QUARANTINE_RECORD_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    HARD_REJECTED_ROW_COUNT NUMBER(18, 0) NOT NULL DEFAULT 0,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    ERROR_MESSAGE VARCHAR,
    PRIMARY KEY (BATCH_ID, SOURCE_FILE)
);

CREATE TABLE IF NOT EXISTS SUPPLY_CHAIN_DEV.RAW.INGESTION_QUARANTINE (
    QUARANTINE_ID VARCHAR NOT NULL,
    BATCH_ID VARCHAR NOT NULL,
    ENTITY_NAME VARCHAR NOT NULL,
    BUSINESS_KEY VARCHAR NOT NULL,
    SOURCE_FILE VARCHAR NOT NULL,
    SOURCE_SYSTEM VARCHAR NOT NULL,
    ROW_HASH VARCHAR NOT NULL,
    QUALITY_STATUS VARCHAR NOT NULL,
    QUALITY_ISSUES ARRAY NOT NULL,
    SOURCE_PAYLOAD VARIANT NOT NULL,
    QUARANTINED_AT TIMESTAMP_TZ NOT NULL,
    PRIMARY KEY (QUARANTINE_ID)
);
