"""CSV column contracts for the synthetic operational system."""

TABLE_COLUMNS: dict[str, list[str]] = {
    "products": [
        "product_id",
        "sku",
        "product_name",
        "category",
        "subcategory",
        "unit_cost",
        "list_price",
        "launch_date",
        "active_flag",
        "reorder_point",
    ],
    "warehouses": [
        "warehouse_id",
        "warehouse_name",
        "region",
        "country",
        "capacity_units",
    ],
    "suppliers": [
        "supplier_id",
        "supplier_name",
        "region",
        "country",
        "lead_time_days",
        "lead_time_std_days",
        "on_time_rate",
        "quality_rate",
        "cost_factor",
        "active_flag",
    ],
    "customers": [
        "customer_id",
        "customer_segment",
        "region",
        "country",
        "signup_date",
    ],
    "orders": [
        "order_id",
        "order_line_id",
        "order_date",
        "customer_id",
        "product_id",
        "warehouse_id",
        "quantity",
        "unit_price",
        "discount_pct",
        "status",
        "promised_delivery_date",
    ],
    "inventory_snapshots": [
        "snapshot_date",
        "warehouse_id",
        "product_id",
        "on_hand_units",
        "reserved_units",
        "available_units",
        "in_transit_units",
        "inventory_value",
    ],
    "purchase_orders": [
        "purchase_order_id",
        "po_line_id",
        "supplier_id",
        "warehouse_id",
        "product_id",
        "order_date",
        "expected_delivery_date",
        "received_date",
        "ordered_quantity",
        "received_quantity",
        "unit_cost",
        "status",
    ],
    "shipments": [
        "shipment_id",
        "order_line_id",
        "warehouse_id",
        "ship_date",
        "delivery_date",
        "shipped_quantity",
        "shipment_status",
        "carrier",
    ],
    "returns": [
        "return_id",
        "order_line_id",
        "return_date",
        "quantity",
        "reason",
        "disposition",
        "refund_amount",
    ],
}
